"""Conclusion summary generation (split from reflection.py — refactor/merger-pipeline style).

`generate_conclusion_summary` is a module-level function taking the LLM
explicitly.  Hybrid approach: structured fields extracted from AgentState
via template (no LLM cost), `summary` field via a lightweight LLM call.
"""

from typing import Any, Dict


def generate_conclusion_summary(quick_thinking_llm: Any, current_state: Dict[str, Any]) -> Dict[str, Any]:
    """Generate a structured lightweight conclusion summary for cross-session memory.

    Hybrid approach:
    - Structured fields: extracted from AgentState via template (no LLM cost)
    - summary field: generated by a lightweight LLM call (~50-100 tokens)

    Args:
        quick_thinking_llm: LLM client (only used for the one-line summary)
        current_state: The final AgentState after analysis completes

    Returns:
        Dict containing: ticker, trade_date, summary, dimensions, final_decision,
        confidence, key_reasons, risks
    """
    ticker = current_state.get("company_of_interest", "UNKNOWN")
    trade_date = str(current_state.get("trade_date", ""))

    # ── Template-based extraction (no LLM cost) ─────────────────────────────
    decision_blocks = current_state.get("decision_blocks") or {}
    investment_plan = decision_blocks.get("investment_plan", "")
    trader_plan = decision_blocks.get("trader_plan", "")
    final_decision = decision_blocks.get("final_trade_decision", "")

    investment_debate = current_state.get("investment_debate_state") or {}
    judge_decision = investment_debate.get("judge_decision", "")

    risk_debate = current_state.get("risk_debate_state") or {}
    risk_judge = risk_debate.get("judge_decision", "")

    bull_history = investment_debate.get("bull_history", "")
    bear_history = investment_debate.get("bear_history", "")

    # Build key_reasons and risks lists
    key_reasons = []
    risks = []

    if bull_history and len(bull_history) > 10:
        key_reasons.append(f"Bull case: {bull_history[:300]}")
    if judge_decision and len(judge_decision) > 10:
        key_reasons.append(f"Investment judgment: {judge_decision[:300]}")
    if risk_judge and len(risk_judge) > 10:
        risks.append(f"Risk judgment: {risk_judge[:300]}")

    # Extract dimensions from screener_context
    dimensions = {}
    screener_context = current_state.get("screener_context") or {}
    route_decision = screener_context.get("route_decision") or {}
    signal_card = route_decision.get("signal_card") or {}
    if isinstance(signal_card, dict):
        dimensions = {
            "policy": signal_card.get("policy_signal_score", 0.5),
            "technical": signal_card.get("technical_signal_score", 0.5),
            "smart_money": signal_card.get("smart_money_signal_score", 0.5),
        }

    # Determine confidence level
    confidence = "中"
    if final_decision:
        dl = final_decision.upper()
        if "强" in final_decision or "买入" in final_decision or "BUY" in dl:
            confidence = "高"
        elif "不" in final_decision or "卖出" in final_decision or "SELL" in dl:
            confidence = "低"
    if judge_decision and ("不" in judge_decision or "无" in judge_decision):
        confidence = "低"

    # ── LLM-generated one-line summary (hybrid part) ───────────────────────
    prompt = (
        f"Given the following analysis results for {ticker} on {trade_date}, "
        f"write ONE concise sentence (in Chinese, under 50 characters) that captures the core investment conclusion.\n\n"
        f"Investment plan: {investment_plan[:500]}\n"
        f"Final decision: {final_decision[:500]}\n"
        f"Judge opinion: {judge_decision[:300]}\n"
        f"Risk opinion: {risk_judge[:300]}"
    )

    summary_text = "分析完成"
    try:
        messages = [{"role": "user", "content": prompt}]
        response = quick_thinking_llm.invoke(messages)
        if hasattr(response, "content") and response.content:
            summary_text = response.content.strip()[:200]
    except Exception:
        summary_text = f"分析完成，结论：{final_decision[:100] if final_decision else '待确认'}"

    return {
        "ticker": ticker,
        "trade_date": trade_date,
        "summary": summary_text,
        "dimensions": dimensions,
        "final_decision": final_decision[:500] if final_decision else "N/A",
        "confidence": confidence,
        "key_reasons": key_reasons[:5],
        "risks": risks[:5],
    }
